#include <yudb/page.h>

const PageId kPageInvalidId = -1;
const PageOffset kPageInvalidOffset = -1;

LIBYUC_CONTAINER_VECTOR_DEFINE(PageId, PageId, LIBYUC_BASIC_ALLOCATOR_DEFALUT, LIBYUC_CONTAINER_VECTOR_DEFAULT_CALLBACKER)
LIBYUC_CONTAINER_HASH_TABLE_DEFINE(PageId, PageId, PageId, LIBYUC_BASIC_ALLOCATOR_DEFALUT, LIBYUC_CONTAINER_HASH_TABLE_DEFAULT_ACCESSOR, LIBYUC_BASIC_MOVER_DEFALUT, LIBYUC_CONTAINER_HASH_TABLE_DEFAULT_HASHER, LIBYUC_BASIC_COMPARER_DEFALUT)