#include <yudb/page.h>

const PageId kPageInvalidId = -1;
const PageOffset kPageInvalidOffset = -1;

LIBYUC_CONTAINER_VECTOR_DEFINE(
        PageId, 
        LIBYUC_CONTAINER_VECTOR_MODE_DYNAMIC,
        PageCount,
        PageCount,
        PageId,
        PageId,
        LIBYUC_CONTAINER_VECTOR_ACCESSOR_DEFAULT,
        LIBYUC_BASIC_ALLOCATOR_DEFALUT, 
        LIBYUC_CONTAINER_VECTOR_CALLBACKER_DEFAULT,
        LIBYUC_CONTAINER_VECTOR_COMPARER_INVALID,
        LIBYUC_CONTAINER_VECTOR_REFERENCER_DEFALUT
)

LIBYUC_CONTAINER_HASH_TABLE_DEFINE(
        PageId,
        PageCount,
        PageId, 
        PageId, 
        LIBYUC_BASIC_ALLOCATOR_DEFALUT, 
        LIBYUC_CONTAINER_HASH_TABLE_DEFAULT_ACCESSOR, 
        LIBYUC_BASIC_MOVER_DEFALUT, 
        LIBYUC_CONTAINER_HASH_TABLE_DEFAULT_HASHER, 
        LIBYUC_BASIC_COMPARER_DEFALUT
)