#include <yudb/page.h>

const PageId kPageInvalidId = -1;
const PageOffset kPageInvalidOffset = -1;

LIBYUC_CONTAINER_VECTOR_DEFINE(PageId, PageId, LIBYUC_OBJECT_ALLOCATOR_DEFALUT, LIBYUC_CONTAINER_VECTOR_DEFAULT_CALLBACKER)
LIBYUC_CONTAINER_HASH_TABLE_DEFINE(PageId, PageId, PageId, LIBYUC_OBJECT_ALLOCATOR_DEFALUT, LIBYUC_CONTAINER_HASH_TABLE_DEFAULT_ACCESSOR, LIBYUC_OBJECT_MOVER_DEFALUT, LIBYUC_CONTAINER_HASH_TABLE_DEFAULT_HASHER, LIBYUC_OBJECT_COMPARER_DEFALUT)